"""Global-level structure-function coupling confirmatory pipeline.

Purpose
-------
Run confirmatory analyses for global connectivity-derived subtypes (structure-
function coupling). This script orchestrates per-modality (functional,
structural, SFC) quantile regression tests (implemented in R via rpy2), applies
multiple-testing correction, and produces violin plots that compare Control,
Depression, and subtype cluster distributions with annotated significance.

High-level steps
----------------
1. Initialize the R environment and ensure required R package is available
   (quantreg).
2. For each connectivity modality in ``CONNECTIVITY_TYPES``:
   - Load the combined cohort table (``ALL_COMBINED``) which must contain
     subject IDs, group labels, per-modality connectivity summary columns,
     cluster labels, demographic and covariates.
   - Run quantile regression (median, tau=0.5) to test: Depression vs
     Control; Cluster 0 vs Control; Cluster 1 vs Control; Cluster 0 vs
     Cluster 1 (via ``run_quantile_regression`` in the utils module).
   - Apply FDR correction to the returned p-values (``apply_multiple_testing_correction``).
   - Create and save violin plots with significance brackets (``create_violin_plot_with_significance``).
3. Save per-modality run logs and FDR result logs to disk.

Expected inputs
---------------
- ``ALL_COMBINED`` (module-level constant): a CSV-like ``pandas.DataFrame``
  with at least the following columns for each modality ``ct`` used by the
  pipeline:
  - ``eid`` : subject identifier (string)
  - ``Group`` : 'Control' or 'Depression' (or a numeric 0/1 mapping)
  - ``{ct}_connectivity`` : scalar connectivity summary used as dependent var
  - cluster label column (configured by ``CLUSTER_COL``; e.g. ``sfc_cluster``)
  - demographic columns: ``p21003_i2`` (age), ``p31`` (sex)
  - motion columns: ``p24441_i2`` (fMRI), ``p24453_i2`` (dMRI) or equivalent
  - optional ICD indicator columns matching ``ICD_COVARIATES``
- This dataframe has normally already been generated by executing 'global_clustering_main.py' and saved to disk as a CSV, then 
reloaded here for analysis.

Outputs and side effects
------------------------
- Per-modality run log: ``<DEPRESSION_DIR>/global_{conn_type}_connectivity_output_sfc_clusters.txt``
- Per-modality FDR log: ``<DEPRESSION_DIR>/global_{conn_type}_connectivity_FDR_sfc_clusters.txt``
- Violin plot PNG per modality: ``<VALIDATION_PLOTS_BASE_DIR>/sfc_con/{conn_type}_global_conn_sfc_confirmatory_violinplots.png``
- The R wrapper writes a temporary CSV to ``/tmp/combined_data.csv`` when
  calling R; this file is overwritten on each call (avoid concurrent runs
  or modify the utilities to use unique tempfiles).

Configuration (important module-level constants)
-----------------------------------------------
- ``CONNECTIVITY_TYPES`` : list of modalities to process (default
  ``['functional','structural','sfc']``)
- ``ICD_COVARIATES`` : list of ICD covariate column names used in QR
- ``QUANTILE_REGRESSION_BOOTSTRAP_R`` : bootstrap iterations passed to R
- Paths: ``DEPRESSION_DIR``, ``COHORTS_DIR``, ``VALIDATION_PLOTS_BASE_DIR``
- Column tokens: ``CLUSTER_COL``, ``GROUP_COL``

Runtime requirements
--------------------
- Python packages: numpy, pandas, matplotlib, seaborn, sklearn, statsmodels,
  rpy2
- System R installation with package: ``quantreg`` (the
  utils try to install ``quantreg`` if missing)

Notes and recommendations
-------------------------
- The utility module handles label normalization (mapping 0/1 to
  ``Cluster 0``/``Cluster 1`` and mapping Group 0/1 to Control/Depression).

"""

import os
import sys
import io
from contextlib import contextmanager
import pandas as pd

# Import all utility functions
from clusters.global_clustering_confirmatory_utils import (
    setup_r_environment,
    apply_multiple_testing_correction,
    get_motion_columns,
    run_quantile_regression,
    create_violin_plot_with_significance,
)

# ==============================================================================
# CONFIGURATION
# ==============================================================================
# Connectivity types to analyze in a single run
CONNECTIVITY_TYPES = ['functional', 'structural', 'sfc']

# ICD-10 codes to include as covariates in quantile regression (comorbidity adjustment)
ICD_COVARIATES = ['I10', 'Z864', 'F419'] # these are the most common comorbidities in depression cohort, based on cohort_selection_main.py

# Progress reporting cadence (subjects)
PROGRESS_EVERY = int(os.getenv('GC_PROGRESS_EVERY', '50'))

# Data paths
DEPRESSION_DIR ='.../F32_notask_STRCO_RSSCHA_RSTIA'
ALL_COMBINED = pd.read_csv('.../global_merged_connectivity_clusters.csv')

# Output directories
VALIDATION_PLOTS_BASE_DIR = '.../schaefer1000+tian54'
COHORTS_DIR = '.../data/UKB/cohorts'

# Motion metrics (column names in head_motion.csv)
fMRI_MOTION_METRIC = 'p24441_i2'  # Framewise displacement for fMRI
dMRI_MOTION_METRIC = 'p24453_i2'  # Mean relative head motion for dMRI

# Cluster and group labels in dataset for quantile regression
CLUSTER_COL = 'sfc_cluster'
GROUP_COL = 'Group'

# Bootstrap iterations for quantile regression (R) standard errors and confidence intervals
QUANTILE_REGRESSION_BOOTSTRAP_R = 5000

# ==============================================================================
# OUTPUT CAPTURE SETUP
# ==============================================================================
class Tee(io.TextIOBase):
  """File-like object that writes to both stdout and buffer."""
  def __init__(self, original, buffer):
    self.original = original
    self.buffer = buffer
    
  def write(self, s):
    self.original.write(s)
    self.buffer.write(s)
    return len(s)
    
  def flush(self):
    self.original.flush()
    self.buffer.flush()


@contextmanager
def capture_stdout_to_log(log_path):
  """Mirror stdout to a buffer and persist it to disk when the block ends."""
  original_stdout = sys.stdout
  buffer = io.StringIO()
  sys.stdout = Tee(original_stdout, buffer)
  try:
    yield buffer
  finally:
    sys.stdout = original_stdout
    with open(log_path, 'w') as log_file:
      log_file.write(buffer.getvalue())

# ==============================================================================
# MAIN PIPELINE
# ==============================================================================
def execute_pipeline_for_conn_type(conn_type, combined_df, validation_plots_dir,
                   motion_columns, fdr_log_path, icd_covariates, cluster_col, group_col):
  """Run the full pipeline for a specific connectivity modality."""

  # ------------------------------------------------------------------
  # STEP 1: Quantile regression analysis (R)
  # ------------------------------------------------------------------
  print("\n[STEP 1] Quantile regression analysis...")
  motion_covariate_list = list(motion_columns.values())
  results = run_quantile_regression(
    combined_df,
    conn_type,
    icd_covariates,
    motion_covariates=motion_covariate_list,
    tau=0.5,
    R=QUANTILE_REGRESSION_BOOTSTRAP_R,
    dependent_var=f'{conn_type}_connectivity',
    cluster_col=cluster_col,
    group_col=group_col,
  )

  print("[RAW P-VALUES USED FOR FDR]")
  for name, value in results['p_values'].items():
    print(f"  {name}: {value}")

  _, corrected_p_values = apply_multiple_testing_correction(
    p_values=list(results['p_values'].values()),
    test_methods=[
      'QR (median) depression vs control',
      'QR (median) cluster 0 vs control',
      'QR (median) cluster 1 vs control',
      'QR (median) cluster 0 vs cluster 1'
    ],
    variable_names=[f'Global {conn_type.capitalize()} Connectivity'] * 4,
    log_path=fdr_log_path
  )

  # ------------------------------------------------------------------
  # STEP 2: Violin plot with significance brackets
  # ------------------------------------------------------------------
  print("\n[STEP 2] Creating violin plot with significance brackets...")
  subject_scalar_control = combined_df[combined_df[group_col] == 'Control'][f'{conn_type}_connectivity']
  subject_scalar_depression = combined_df[combined_df[group_col] == 'Depression'][f'{conn_type}_connectivity']
  
  # Ensure cluster labels 'Cluster 0'/'Cluster 1' are converted to integers 0/1
  clusters = combined_df.loc[combined_df[group_col] == 'Depression', cluster_col].copy()
  clusters = clusters.replace({'Cluster 0': 0, 'Cluster 1': 1})
  clusters = clusters.astype(int)

  create_violin_plot_with_significance(
    subject_scalar_control,
    subject_scalar_depression,
    clusters,
    corrected_p_values,
    conn_type,
    os.path.join(validation_plots_dir, f'{conn_type}_global_conn_sfc_confirmatory_violinplots.png')
  )

  print(f"\n{'-'*80}")
  print(f"Completed {conn_type} connectivity analysis")
  print(f"{'-'*80}")


def run_pipeline_for_conn_type(conn_type, cohort_data):
  """Wrapper that sets up per-modality paths, logging, and execution."""

  validation_plots_dir = os.path.join(VALIDATION_PLOTS_BASE_DIR, f'sfc_con')

  general_log_path = os.path.join(DEPRESSION_DIR, f'global_{conn_type}_connectivity_output_sfc_clusters.txt')
  fdr_log_path = os.path.join(DEPRESSION_DIR, f'global_{conn_type}_connectivity_FDR_sfc_clusters.txt')
  motion_columns = get_motion_columns(conn_type, fMRI_MOTION_METRIC, dMRI_MOTION_METRIC)

  display_conn = "Structure-Function Coupling" if str(conn_type).lower() == "sfc" else str(conn_type).upper()
  print(f"\n{'='*80}")
  print(f"GLOBAL CONNECTIVITY PIPELINE — {display_conn}")
  print(f"{'='*80}\n")

  with capture_stdout_to_log(general_log_path):
    execute_pipeline_for_conn_type(
      conn_type=conn_type,
      combined_df=cohort_data,
      validation_plots_dir=validation_plots_dir,
      motion_columns=motion_columns,
      fdr_log_path=fdr_log_path,
      icd_covariates=ICD_COVARIATES,
      cluster_col=CLUSTER_COL,
      group_col=GROUP_COL,
    )

  print(f"Saved run log to: {general_log_path}")
  print(f"Saved FDR correction log to: {fdr_log_path}\n")


def main():
  """Execute the complete global connectivity clustering pipeline for all modalities."""

  print(f"\n{'='*80}")
  print("Global-level Depression Subtyping Pipeline — Confirmatory Analysis")
  display_modalities = [
    "Structure-Function Coupling" if str(ct).lower() == "sfc" else str(ct)
    for ct in CONNECTIVITY_TYPES
  ]
  print(f"Modalities queued: {', '.join(display_modalities)}")
  print(f"{'='*80}\n")

  print("[STEP 1] Initializing R environment once...")
  setup_r_environment()
  print("R packages loaded: quantreg, multcomp")

  print("\n[STEP 2] Loading cohort data...")

  for conn_type in CONNECTIVITY_TYPES:
    run_pipeline_for_conn_type(conn_type, ALL_COMBINED)

  print(f"\n{'='*80}")
  print("ALL MODALITIES COMPLETE")
  print(f"{'='*80}\n")


if __name__ == "__main__":
  main()