
"""
Top-level orchestration script for the module-level depression subtyping
pipeline.

Purpose
-------
This script coordinates data loading, per-subject module connectivity
computation, module-level aggregation, clustering, statistical testing,
and visualization. It wires together utility functions implemented in
`source_code/clusters/module_clustering_utils.py` to produce the
end-to-end analysis and outputs used in reports and figures.

High-level steps
----------------
1. Load combined cohort metadata and identify subject IDs by group.
2. For each subject, compute per-module internal/external connectivity
     for functional and structural modalities, and compute internal/external
     structure-function coupling (SFC). Save per-subject CSV outputs.
3. Aggregate per-subject module connectivity into a wide `final_df`
     (subjects × module-features) and save a CSV copy.
4. Plot per-module distributions and cohort-specific module histograms.
5. Compute Spearman correlation matrices of module features and
     generate FDR-significant heatmaps.
6. Perform hierarchical clustering on module-level features and run
     bootstrap stability analysis to assign cluster labels (Cluster 0/1).
7. Compute clustering validation metrics (silhouette, Calinski-Harabasz)
     and save a validation summary CSV.
8. Analyze cross-modality agreement across connectivity solutions.
9. Merge covariates, test covariate associations (with PNG, CSV and TXT outputs), run quantile regression (via `rpy2` + R `quantreg`),
     FDR-correct tests across modules, and annotate violin plots.
10. Create brain maps summarizing cluster profile differences
        (optionally saving NIfTI masks for significant modules).

Inputs and expected files
-------------------------
- `COMBINED_COHORT_PATH`: path to combined cohort CSV (must include `eid`
    and `depression_status` or similar group identifier).
- Per-subject connectivity matrices located under cohort directories
    (e.g., `DEPRESSION_DIR/{eid}/i2/{eid}_functional_connectivity_matrix_reordered.npy`).
- `COMMUNITY_LABELS_PATH`: text file containing community labels mapping
    atlas ROIs → module IDs (used to aggregate ROI-level signals to modules).
- `ATLAS_FILE`: parcellation NIfTI used for brain visualizations.

Configuration and constants
---------------------------
The top of this module exposes a set of global configuration constants
that control which connectivity types and directions are processed,
paths for input data, and output directories. Key variables include:

- `CONNECTIVITY_TYPES` / `DIRECTION_TYPES`: modality and direction lists.
- `ICD_10_COVARIATES`: list of ICD-10 comorbidity column names to include
    as covariates in regression and covariate summary plots.
- `PROGRESS_EVERY`: frequency (subjects) at which progress messages are
    printed during per-subject processing.
- `CLUSTER_STABILITY_BOOTSTRAP_ITER`: number of bootstrap iterations for
    cluster stability analysis.
- File/directory paths such as `DEPRESSION_DIR`, `CONTROL_DIR`,
    `GENERAL_DIR`, `PLOTS_DIR`, and `FIGURES_DIR` specify where inputs are
    read and outputs are written.

Outputs
-------
The pipeline writes a set of CSVs, PNG figures, and optional NIfTI
volumes. Notable outputs:

- `module_connectivity_wide.csv`: combined wide table of per-subject
    module features saved under `GENERAL_DIR`.
- `module_connectivity_features_with_clusters.csv`: feature table with
    cluster assignments written after hierarchical clustering.
- 'module_connectivity_features_with_covariates.csv': previous table merged 
    with covariates for regression. This is the final combined table used for all downstream analyses.
- `module_connectivity_clustering_validation.csv`: validation metrics
    (silhouette and Calinski-Harabasz) per tested k.
- Multiple PNG figures under `PLOTS_DIR` / `FIGURES_DIR`, including
    distribution histograms, correlation matrices, violin plots, heatmaps,
    and brain maps. Optionally saved NIfTI masks live in
    `{FIGURES_DIR}/nifti_masks/` when enabled.

Assumptions and column conventions
----------------------------------
- Per-subject feature CSVs generated by `compute_and_save_module_connectivity`
    follow the naming conventions used in the utilities (e.g.,
    `'{module}_internal_functional'`, `'{module}_external_structural'`).
- The combined `final_df` must include `eid` and `depression_status` (0/1),
    and cluster assignment columns created by the clustering step are named
    `'{conn_type}_{dir_type}_cluster'`.

Notes and troubleshooting
-------------------------
- Many functions depend on third-party neuroimaging and statistics
    libraries (nibabel, nilearn, scipy, statsmodels, rpy2). Ensure the
    environment has these installed and that R is available for quantile
    regression steps.

"""

import os
import sys
import io
from contextlib import contextmanager
import numpy as np

sys.path.append('source_code')

from clusters.module_clustering_utils import (
    setup_r_environment,
    load_combined_cohort_data,
    get_subject_ids_by_status,
    compute_and_save_module_connectivity,
    build_module_connectivity_dataframe,
    plot_module_metric_distributions,
    plot_module_correlation_matrices,
    perform_module_hierarchical_clustering,
    compute_clustering_validation,
    plot_clustering_validation_metrics,
    analyze_cross_modality_agreement,
    merge_covariates_for_module,
    determine_covariate_distributions,
    run_module_quantile_regression_pipeline,
    plot_cluster_feature_brainmaps,
)

# ==============================================================================
# CONFIGURATION
# ==============================================================================

CONNECTIVITY_TYPES = ('functional', 'structural', 'sfc')
DIRECTION_TYPES = ('internal', 'external')
ICD_10_COVARIATES = ['I10', 'Z864', 'F419']
PROGRESS_EVERY = int(os.getenv('MC_PROGRESS_EVERY', '50'))

DEPRESSION_DIR = '.../F32_notask_STRCO_RSSCHA_RSTIA'
CONTROL_DIR = '.../control_notask_STRCO_RSSCHA_RSTIA'
GENERAL_DIR = '.../UKB/cohorts'
COMBINED_COHORT_PATH = '.../UKB/cohorts/combined_cohort_F32.csv'

PLOTS_DIR = '.../schaefer1000+tian54'
FIGURES_DIR = '.../schaefer1000+tian54'

# Motion metrics (column names in head_motion.csv)
fMRI_MOTION_METRIC = 'p24441_i2'  # Framewise displacement for fMRI
dMRI_MOTION_METRIC = 'p24453_i2'  # Mean relative head motion for dMRI

COMMUNITY_LABELS_PATH = '.../notebooks/CM.txt'
ATLAS_FILE = '.../Schaefer1000_TianS4_combined.nii.gz'

# Bootstrap iterations for quantile regression (R) standard errors and confidence intervals
QUANTILE_REGRESSION_BOOTSTRAP_R = 5000
# Bootstrap iterations for clustering stability analysis
CLUSTER_STABILITY_BOOTSTRAP_ITER = 5000

# ==============================================================================
# OUTPUT CAPTURE SETUP
# ==============================================================================
class Tee(io.TextIOBase):
    """File-like object that writes to both stdout and buffer."""

    def __init__(self, original, buffer):
        self.original = original
        self.buffer = buffer

    def write(self, s):
        self.original.write(s)
        self.buffer.write(s)
        return len(s)

    def flush(self):
        self.original.flush()
        self.buffer.flush()


@contextmanager
def capture_stdout_to_log(log_path):
    """Mirror stdout to a buffer and persist it to disk when the block ends."""
    original_stdout = sys.stdout
    buffer = io.StringIO()
    sys.stdout = Tee(original_stdout, buffer)
    try:
        yield buffer
    finally:
        sys.stdout = original_stdout
        with open(log_path, 'w') as log_file:
            log_file.write(buffer.getvalue())


# ==============================================================================
# MAIN PIPELINE
# ==============================================================================
def main():
    print("=" * 80)
    print("Module-level Depression Subtyping Pipeline")
    print("=" * 80)

    os.makedirs(PLOTS_DIR, exist_ok=True)
    os.makedirs(FIGURES_DIR, exist_ok=True)

    # ------------------------------------------------------------------
    # STEP 1: Initialize R environment
    # ------------------------------------------------------------------
    print("\n[STEP 1/9] Initializing R environment...")
    setup_r_environment()

    # ------------------------------------------------------------------
    # STEP 2: Load cohort data
    # ------------------------------------------------------------------
    print("\n[STEP 2/9] Loading cohort data...")
    data = load_combined_cohort_data(COMBINED_COHORT_PATH)
    depressed_subject_ids, control_subject_ids = get_subject_ids_by_status(data)
    print(f"Found {len(depressed_subject_ids)} depressed subjects in cohort F32.")
    print(f"Found {len(control_subject_ids)} control subjects in cohort control.")

    # ------------------------------------------------------------------
    # STEP 3: Compute module connectivity and coupling per subject
    # ------------------------------------------------------------------
    print("\n[STEP 3/9] Computing module connectivity and coupling features...")
    CM = np.loadtxt(COMMUNITY_LABELS_PATH)

    print("Processing cohort F32...")
    compute_and_save_module_connectivity(
        DEPRESSION_DIR,
        depressed_subject_ids,
        CM,
        progress_every=PROGRESS_EVERY,
        sfc_warning_log_dir=os.path.join(GENERAL_DIR, 'sfc_warning_logs'),
        cohort_label='F32',
    )

    print("Processing cohort control...")
    compute_and_save_module_connectivity(
        CONTROL_DIR,
        control_subject_ids,
        CM,
        progress_every=PROGRESS_EVERY,
        sfc_warning_log_dir=os.path.join(GENERAL_DIR, 'sfc_warning_logs'),
        cohort_label='control',
    )

    # ------------------------------------------------------------------
    # STEP 4: Build module connectivity dataframe
    # ------------------------------------------------------------------
    print("\n[STEP 4/9] Building module connectivity dataframe...")
    final_df, mods = build_module_connectivity_dataframe(
        DEPRESSION_DIR,
        CONTROL_DIR,
        depressed_subject_ids,
        control_subject_ids,
    )
    final_df.to_csv(os.path.join(GENERAL_DIR, 'module_connectivity_wide.csv'), index=False)
    print("Combined (wide) module connectivity data shape:", final_df.shape)

    # ------------------------------------------------------------------
    # STEP 5: Distributions and correlations
    # ------------------------------------------------------------------
    print("\n[STEP 5/9] Plotting module metric distributions...")
    plot_module_metric_distributions(final_df, mods, PLOTS_DIR)

    print("\n[STEP 5/9] Plotting module correlation matrices...")
    plot_module_correlation_matrices(final_df, PLOTS_DIR)

    # ------------------------------------------------------------------
    # STEP 6: Hierarchical clustering and bootstrap stability
    # ------------------------------------------------------------------
    print("\n[STEP 6/9] Hierarchical clustering and bootstrap stability...")
    final_df = perform_module_hierarchical_clustering(
        final_df,
        PLOTS_DIR,
        FIGURES_DIR,
        conn_types=CONNECTIVITY_TYPES,
        dir_types=DIRECTION_TYPES,
        n_clusters=2,
        bootstrap_iter=CLUSTER_STABILITY_BOOTSTRAP_ITER,
    )
    final_df.to_csv(
        os.path.join(GENERAL_DIR, 'module_connectivity_features_with_clusters.csv'),
        index=False,
    )
    print("Saved module connectivity features with cluster assignments to CSV.")

    # ------------------------------------------------------------------
    # STEP 7: Clustering validation
    # ------------------------------------------------------------------
    print("\n[STEP 7/9] Clustering validation...")
    validation_df, summary = compute_clustering_validation(
        final_df,
        conn_types=CONNECTIVITY_TYPES,
        dir_types=DIRECTION_TYPES,
    )
    validation_df.to_csv(
        os.path.join(GENERAL_DIR, 'module_connectivity_clustering_validation.csv'),
        index=False,
    )
    for row in summary:
        print(
            f"Best clustering validation - {row['connectivity_type']} {row['direction_type']} "
            f"k={row['best_k_silhouette']}: Silhouette={row['best_silhouette_score']:.4f}, "
            f"Calinski-Harabasz={row['best_calinski_harabasz_score']:.4f}"
        )
    plot_clustering_validation_metrics(validation_df, PLOTS_DIR)

    # ------------------------------------------------------------------
    # STEP 8: Cross-modality agreement
    # ------------------------------------------------------------------
    print("\n[STEP 8/9] Cross-modality agreement analysis...")
    analyze_cross_modality_agreement(GENERAL_DIR, PLOTS_DIR)

    # ------------------------------------------------------------------
    # STEP 9: Covariates, quantile regression, and cluster profiles
    # ------------------------------------------------------------------
    print("\n[STEP 9/9] Covariates, quantile regression, and cluster profiles...")
    covariate_columns = [
        'eid',
        'p21003_i2',
        'p31',
        'I10',
        'Z864',
        'F419',
        'p24453_i2',
        'p24441_i2',
    ]
    merged, colname_map = merge_covariates_for_module(
        final_df,
        data,
        covariate_columns,
        GENERAL_DIR,
        output_basename='module_connectivity_features_with_covariates',
    )

    determine_covariate_distributions(
        combined_df=merged,
        available_types=[],
        motion_metric=fMRI_MOTION_METRIC,
        out_dir=PLOTS_DIR,
        cohorts_dir=None,
        icd_covariates=ICD_10_COVARIATES,
        conn_types=list(CONNECTIVITY_TYPES),
        dir_types=list(DIRECTION_TYPES),
    )

    brainmap_significance = run_module_quantile_regression_pipeline(
        merged=merged,
        final_df=final_df,
        mods=mods,
        R=QUANTILE_REGRESSION_BOOTSTRAP_R,
        conn_types=CONNECTIVITY_TYPES,
        dir_types=DIRECTION_TYPES,
        icd_covariates=ICD_10_COVARIATES,
        fMRI_MOTION_METRIC=fMRI_MOTION_METRIC,
        dMRI_MOTION_METRIC=dMRI_MOTION_METRIC,
        plots_dir=PLOTS_DIR,
        depressed_subjects_dir=DEPRESSION_DIR,
        colname_map=colname_map,
    )

    final_df_clusters = final_df.loc[final_df['depression_status'] == 1].reset_index(drop=True)
    cluster_cols = [
        f'{conn}_{dir_type}_cluster'
        for conn in CONNECTIVITY_TYPES
        for dir_type in DIRECTION_TYPES
    ]
    feature_df = final_df_clusters.drop(
        columns=[c for c in ['eid', 'depression_status'] + cluster_cols if c in final_df_clusters.columns]
    ).copy()

    plot_cluster_feature_brainmaps(
        final_df=final_df_clusters,
        feature_df=feature_df.assign(eid=final_df_clusters['eid']),
        atlas_img_path=ATLAS_FILE,
        community_labels=CM,
        fig_dir=FIGURES_DIR,
        modules=mods,
        minmax=True,
        significance_map=brainmap_significance,
        pvalue_threshold=0.05,
    )

    print("\nAnalysis complete!")
    print(f"Saved following outputs:")
    print(f" - Main dataset: {os.path.join(GENERAL_DIR, 'module_connectivity_features_with_covariates.csv')}")
    print(f" - Brainmap figures directory: {FIGURES_DIR}")
    print(f" - Plots directory: {PLOTS_DIR}")


if __name__ == '__main__':
    log_path = os.path.join(DEPRESSION_DIR, 'module_connectivity_output.txt')
    with capture_stdout_to_log(log_path):
        main()
